//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference3
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IWTpIntegradoras")]
    public interface IWTpIntegradoras
    {
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do wrapper (urn:WTpIntegr-IWTpIntegradoras) da mensagem InsDadosIntegRequest não corresponde ao valor padrão (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegr-IWTpIntegradoras#InsDadosInteg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServiceReference3.InsDadosIntegResponse InsDadosInteg(ServiceReference3.InsDadosIntegRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegr-IWTpIntegradoras#InsDadosInteg", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference3.InsDadosIntegResponse> InsDadosIntegAsync(ServiceReference3.InsDadosIntegRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegr-IWTpIntegradoras#GetStatusInteg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServiceReference3.GetStatusIntegResponse GetStatusInteg(ServiceReference3.GetStatusIntegRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores retornados.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegr-IWTpIntegradoras#GetStatusInteg", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference3.GetStatusIntegResponse> GetStatusIntegAsync(ServiceReference3.GetStatusIntegRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegr-IWTpIntegradoras#GetDadosInteg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServiceReference3.GetDadosIntegResponse GetDadosInteg(ServiceReference3.GetDadosIntegRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores retornados.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegr-IWTpIntegradoras#GetDadosInteg", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference3.GetDadosIntegResponse> GetDadosIntegAsync(ServiceReference3.GetDadosIntegRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegr-IWTpIntegradoras#GetExpPedidosVenda", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServiceReference3.GetExpPedidosVendaResponse GetExpPedidosVenda(ServiceReference3.GetExpPedidosVendaRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores retornados.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegr-IWTpIntegradoras#GetExpPedidosVenda", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference3.GetExpPedidosVendaResponse> GetExpPedidosVendaAsync(ServiceReference3.GetExpPedidosVendaRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do wrapper (urn:WTpIntegr-IWTpIntegradoras) da mensagem MarcaExpPedidoVendaProcRequest não corresponde ao valor padrão (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegr-IWTpIntegradoras#MarcaExpPedidoVendaProc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServiceReference3.MarcaExpPedidoVendaProcResponse MarcaExpPedidoVendaProc(ServiceReference3.MarcaExpPedidoVendaProcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegr-IWTpIntegradoras#MarcaExpPedidoVendaProc", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference3.MarcaExpPedidoVendaProcResponse> MarcaExpPedidoVendaProcAsync(ServiceReference3.MarcaExpPedidoVendaProcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegr-IWTpIntegradoras#Select", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServiceReference3.SelectResponse Select(ServiceReference3.SelectRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores retornados.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WTpIntegr-IWTpIntegradoras#Select", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference3.SelectResponse> SelectAsync(ServiceReference3.SelectRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:@:WTpBase")]
    public partial class TWRemStatus
    {
        
        private int codeField;
        
        private string msgField;
        
        /// <remarks/>
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Msg
        {
            get
            {
                return this.msgField;
            }
            set
            {
                this.msgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:@:WTpIntegVendas")]
    public partial class TWRemFiltroPedidoVenda
    {
        
        private short empresaField;
        
        private short filialField;
        
        private int pedidoDeField;
        
        private int pedidoAteField;
        
        private int dataPedidoDeField;
        
        private int dataPedidoAteField;
        
        /// <remarks/>
        public short Empresa
        {
            get
            {
                return this.empresaField;
            }
            set
            {
                this.empresaField = value;
            }
        }
        
        /// <remarks/>
        public short Filial
        {
            get
            {
                return this.filialField;
            }
            set
            {
                this.filialField = value;
            }
        }
        
        /// <remarks/>
        public int PedidoDe
        {
            get
            {
                return this.pedidoDeField;
            }
            set
            {
                this.pedidoDeField = value;
            }
        }
        
        /// <remarks/>
        public int PedidoAte
        {
            get
            {
                return this.pedidoAteField;
            }
            set
            {
                this.pedidoAteField = value;
            }
        }
        
        /// <remarks/>
        public int DataPedidoDe
        {
            get
            {
                return this.dataPedidoDeField;
            }
            set
            {
                this.dataPedidoDeField = value;
            }
        }
        
        /// <remarks/>
        public int DataPedidoAte
        {
            get
            {
                return this.dataPedidoAteField;
            }
            set
            {
                this.dataPedidoAteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsDadosInteg", WrapperNamespace="urn:WTpIntegr-IWTpIntegradoras", IsWrapped=true)]
    public partial class InsDadosIntegRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string XmlDados;
        
        public InsDadosIntegRequest()
        {
        }
        
        public InsDadosIntegRequest(string TokenId, string XmlDados)
        {
            this.TokenId = TokenId;
            this.XmlDados = XmlDados;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsDadosIntegResponse", WrapperNamespace="urn:WTpIntegr-IWTpIntegradoras", IsWrapped=true)]
    public partial class InsDadosIntegResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ServiceReference3.TWRemStatus @return;
        
        public InsDadosIntegResponse()
        {
        }
        
        public InsDadosIntegResponse(ServiceReference3.TWRemStatus @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusInteg", WrapperNamespace="urn:WTpIntegr-IWTpIntegradoras", IsWrapped=true)]
    public partial class GetStatusIntegRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string XmlDados;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string XmlRet;
        
        public GetStatusIntegRequest()
        {
        }
        
        public GetStatusIntegRequest(string TokenId, string XmlDados, string XmlRet)
        {
            this.TokenId = TokenId;
            this.XmlDados = XmlDados;
            this.XmlRet = XmlRet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusIntegResponse", WrapperNamespace="urn:WTpIntegr-IWTpIntegradoras", IsWrapped=true)]
    public partial class GetStatusIntegResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ServiceReference3.TWRemStatus @return;
        
        public GetStatusIntegResponse()
        {
        }
        
        public GetStatusIntegResponse(string XmlRet, ServiceReference3.TWRemStatus @return)
        {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDadosInteg", WrapperNamespace="urn:WTpIntegr-IWTpIntegradoras", IsWrapped=true)]
    public partial class GetDadosIntegRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string XmlDados;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string XmlRet;
        
        public GetDadosIntegRequest()
        {
        }
        
        public GetDadosIntegRequest(string TokenId, string XmlDados, string XmlRet)
        {
            this.TokenId = TokenId;
            this.XmlDados = XmlDados;
            this.XmlRet = XmlRet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDadosIntegResponse", WrapperNamespace="urn:WTpIntegr-IWTpIntegradoras", IsWrapped=true)]
    public partial class GetDadosIntegResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ServiceReference3.TWRemStatus @return;
        
        public GetDadosIntegResponse()
        {
        }
        
        public GetDadosIntegResponse(string XmlRet, ServiceReference3.TWRemStatus @return)
        {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetExpPedidosVenda", WrapperNamespace="urn:WTpIntegr-IWTpIntegradoras", IsWrapped=true)]
    public partial class GetExpPedidosVendaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ServiceReference3.TWRemFiltroPedidoVenda Filtro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string XmlRet;
        
        public GetExpPedidosVendaRequest()
        {
        }
        
        public GetExpPedidosVendaRequest(string TokenId, ServiceReference3.TWRemFiltroPedidoVenda Filtro, string XmlRet)
        {
            this.TokenId = TokenId;
            this.Filtro = Filtro;
            this.XmlRet = XmlRet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetExpPedidosVendaResponse", WrapperNamespace="urn:WTpIntegr-IWTpIntegradoras", IsWrapped=true)]
    public partial class GetExpPedidosVendaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ServiceReference3.TWRemStatus @return;
        
        public GetExpPedidosVendaResponse()
        {
        }
        
        public GetExpPedidosVendaResponse(string XmlRet, ServiceReference3.TWRemStatus @return)
        {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MarcaExpPedidoVendaProc", WrapperNamespace="urn:WTpIntegr-IWTpIntegradoras", IsWrapped=true)]
    public partial class MarcaExpPedidoVendaProcRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int empresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int filial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int nro_pedido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int seq_registro;
        
        public MarcaExpPedidoVendaProcRequest()
        {
        }
        
        public MarcaExpPedidoVendaProcRequest(string TokenId, int empresa, int filial, int nro_pedido, int seq_registro)
        {
            this.TokenId = TokenId;
            this.empresa = empresa;
            this.filial = filial;
            this.nro_pedido = nro_pedido;
            this.seq_registro = seq_registro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MarcaExpPedidoVendaProcResponse", WrapperNamespace="urn:WTpIntegr-IWTpIntegradoras", IsWrapped=true)]
    public partial class MarcaExpPedidoVendaProcResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ServiceReference3.TWRemStatus @return;
        
        public MarcaExpPedidoVendaProcResponse()
        {
        }
        
        public MarcaExpPedidoVendaProcResponse(ServiceReference3.TWRemStatus @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Select", WrapperNamespace="urn:WTpIntegr-IWTpIntegradoras", IsWrapped=true)]
    public partial class SelectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ASelect;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string XmlRet;
        
        public SelectRequest()
        {
        }
        
        public SelectRequest(string TokenId, string ASelect, string XmlRet)
        {
            this.TokenId = TokenId;
            this.ASelect = ASelect;
            this.XmlRet = XmlRet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectResponse", WrapperNamespace="urn:WTpIntegr-IWTpIntegradoras", IsWrapped=true)]
    public partial class SelectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string XmlRet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ServiceReference3.TWRemStatus @return;
        
        public SelectResponse()
        {
        }
        
        public SelectResponse(string XmlRet, ServiceReference3.TWRemStatus @return)
        {
            this.XmlRet = XmlRet;
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IWTpIntegradorasChannel : ServiceReference3.IWTpIntegradoras, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WTpIntegradorasClient : System.ServiceModel.ClientBase<ServiceReference3.IWTpIntegradoras>, ServiceReference3.IWTpIntegradoras
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WTpIntegradorasClient() : 
                base(WTpIntegradorasClient.GetDefaultBinding(), WTpIntegradorasClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IWTpIntegradorasPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WTpIntegradorasClient(EndpointConfiguration endpointConfiguration) : 
                base(WTpIntegradorasClient.GetBindingForEndpoint(endpointConfiguration), WTpIntegradorasClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WTpIntegradorasClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WTpIntegradorasClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WTpIntegradorasClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WTpIntegradorasClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WTpIntegradorasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference3.InsDadosIntegResponse ServiceReference3.IWTpIntegradoras.InsDadosInteg(ServiceReference3.InsDadosIntegRequest request)
        {
            return base.Channel.InsDadosInteg(request);
        }
        
        public ServiceReference3.TWRemStatus InsDadosInteg(string TokenId, string XmlDados)
        {
            ServiceReference3.InsDadosIntegRequest inValue = new ServiceReference3.InsDadosIntegRequest();
            inValue.TokenId = TokenId;
            inValue.XmlDados = XmlDados;
            ServiceReference3.InsDadosIntegResponse retVal = ((ServiceReference3.IWTpIntegradoras)(this)).InsDadosInteg(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference3.InsDadosIntegResponse> ServiceReference3.IWTpIntegradoras.InsDadosIntegAsync(ServiceReference3.InsDadosIntegRequest request)
        {
            return base.Channel.InsDadosIntegAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference3.InsDadosIntegResponse> InsDadosIntegAsync(string TokenId, string XmlDados)
        {
            ServiceReference3.InsDadosIntegRequest inValue = new ServiceReference3.InsDadosIntegRequest();
            inValue.TokenId = TokenId;
            inValue.XmlDados = XmlDados;
            return ((ServiceReference3.IWTpIntegradoras)(this)).InsDadosIntegAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference3.GetStatusIntegResponse ServiceReference3.IWTpIntegradoras.GetStatusInteg(ServiceReference3.GetStatusIntegRequest request)
        {
            return base.Channel.GetStatusInteg(request);
        }
        
        public ServiceReference3.TWRemStatus GetStatusInteg(string TokenId, string XmlDados, ref string XmlRet)
        {
            ServiceReference3.GetStatusIntegRequest inValue = new ServiceReference3.GetStatusIntegRequest();
            inValue.TokenId = TokenId;
            inValue.XmlDados = XmlDados;
            inValue.XmlRet = XmlRet;
            ServiceReference3.GetStatusIntegResponse retVal = ((ServiceReference3.IWTpIntegradoras)(this)).GetStatusInteg(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ServiceReference3.GetStatusIntegResponse> GetStatusIntegAsync(ServiceReference3.GetStatusIntegRequest request)
        {
            return base.Channel.GetStatusIntegAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference3.GetDadosIntegResponse ServiceReference3.IWTpIntegradoras.GetDadosInteg(ServiceReference3.GetDadosIntegRequest request)
        {
            return base.Channel.GetDadosInteg(request);
        }
        
        public ServiceReference3.TWRemStatus GetDadosInteg(string TokenId, string XmlDados, ref string XmlRet)
        {
            ServiceReference3.GetDadosIntegRequest inValue = new ServiceReference3.GetDadosIntegRequest();
            inValue.TokenId = TokenId;
            inValue.XmlDados = XmlDados;
            inValue.XmlRet = XmlRet;
            ServiceReference3.GetDadosIntegResponse retVal = ((ServiceReference3.IWTpIntegradoras)(this)).GetDadosInteg(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ServiceReference3.GetDadosIntegResponse> GetDadosIntegAsync(ServiceReference3.GetDadosIntegRequest request)
        {
            return base.Channel.GetDadosIntegAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference3.GetExpPedidosVendaResponse ServiceReference3.IWTpIntegradoras.GetExpPedidosVenda(ServiceReference3.GetExpPedidosVendaRequest request)
        {
            return base.Channel.GetExpPedidosVenda(request);
        }
        
        public ServiceReference3.TWRemStatus GetExpPedidosVenda(string TokenId, ServiceReference3.TWRemFiltroPedidoVenda Filtro, ref string XmlRet)
        {
            ServiceReference3.GetExpPedidosVendaRequest inValue = new ServiceReference3.GetExpPedidosVendaRequest();
            inValue.TokenId = TokenId;
            inValue.Filtro = Filtro;
            inValue.XmlRet = XmlRet;
            ServiceReference3.GetExpPedidosVendaResponse retVal = ((ServiceReference3.IWTpIntegradoras)(this)).GetExpPedidosVenda(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ServiceReference3.GetExpPedidosVendaResponse> GetExpPedidosVendaAsync(ServiceReference3.GetExpPedidosVendaRequest request)
        {
            return base.Channel.GetExpPedidosVendaAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference3.MarcaExpPedidoVendaProcResponse ServiceReference3.IWTpIntegradoras.MarcaExpPedidoVendaProc(ServiceReference3.MarcaExpPedidoVendaProcRequest request)
        {
            return base.Channel.MarcaExpPedidoVendaProc(request);
        }
        
        public ServiceReference3.TWRemStatus MarcaExpPedidoVendaProc(string TokenId, int empresa, int filial, int nro_pedido, int seq_registro)
        {
            ServiceReference3.MarcaExpPedidoVendaProcRequest inValue = new ServiceReference3.MarcaExpPedidoVendaProcRequest();
            inValue.TokenId = TokenId;
            inValue.empresa = empresa;
            inValue.filial = filial;
            inValue.nro_pedido = nro_pedido;
            inValue.seq_registro = seq_registro;
            ServiceReference3.MarcaExpPedidoVendaProcResponse retVal = ((ServiceReference3.IWTpIntegradoras)(this)).MarcaExpPedidoVendaProc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference3.MarcaExpPedidoVendaProcResponse> ServiceReference3.IWTpIntegradoras.MarcaExpPedidoVendaProcAsync(ServiceReference3.MarcaExpPedidoVendaProcRequest request)
        {
            return base.Channel.MarcaExpPedidoVendaProcAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference3.MarcaExpPedidoVendaProcResponse> MarcaExpPedidoVendaProcAsync(string TokenId, int empresa, int filial, int nro_pedido, int seq_registro)
        {
            ServiceReference3.MarcaExpPedidoVendaProcRequest inValue = new ServiceReference3.MarcaExpPedidoVendaProcRequest();
            inValue.TokenId = TokenId;
            inValue.empresa = empresa;
            inValue.filial = filial;
            inValue.nro_pedido = nro_pedido;
            inValue.seq_registro = seq_registro;
            return ((ServiceReference3.IWTpIntegradoras)(this)).MarcaExpPedidoVendaProcAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference3.SelectResponse ServiceReference3.IWTpIntegradoras.Select(ServiceReference3.SelectRequest request)
        {
            return base.Channel.Select(request);
        }
        
        public ServiceReference3.TWRemStatus Select(string TokenId, string ASelect, ref string XmlRet)
        {
            ServiceReference3.SelectRequest inValue = new ServiceReference3.SelectRequest();
            inValue.TokenId = TokenId;
            inValue.ASelect = ASelect;
            inValue.XmlRet = XmlRet;
            ServiceReference3.SelectResponse retVal = ((ServiceReference3.IWTpIntegradoras)(this)).Select(inValue);
            XmlRet = retVal.XmlRet;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ServiceReference3.SelectResponse> SelectAsync(ServiceReference3.SelectRequest request)
        {
            return base.Channel.SelectAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IWTpIntegradorasPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IWTpIntegradorasPort))
            {
                return new System.ServiceModel.EndpointAddress("http://127.0.0.1:1026/soap/IWTpIntegradoras");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WTpIntegradorasClient.GetBindingForEndpoint(EndpointConfiguration.IWTpIntegradorasPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WTpIntegradorasClient.GetEndpointAddress(EndpointConfiguration.IWTpIntegradorasPort);
        }
        
        public enum EndpointConfiguration
        {
            
            IWTpIntegradorasPort,
        }
    }
}
